# Generated by Django 3.0 on 2020-04-29 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=300)),
                ('option_1', models.CharField(max_length=30)),
                ('option_2', models.CharField(max_length=30)),
                ('option_3', models.CharField(max_length=30)),
                ('option_4', models.CharField(max_length=30)),
                ('correct_option', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSet10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('question_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Questions')),
                ('question_10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Questions')),
                ('question_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Questions')),
                ('question_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Questions')),
                ('question_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Questions')),
                ('question_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Questions')),
                ('question_6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Questions')),
                ('question_7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Questions')),
                ('question_8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Questions')),
                ('question_9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Questions')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSet5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('question_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Questions')),
                ('question_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Questions')),
                ('question_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Questions')),
                ('question_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Questions')),
                ('question_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Questions')),
            ],
        ),
        migrations.CreateModel(
            name='Quizs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('questions_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.QuestionSet10')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreBoardModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Quizs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizDestributorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_set10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.QuestionSet10')),
                ('question_set5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.QuestionSet5')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Quizs')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
