# Generated by Django 3.0 on 2020-04-29 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizDestributorModel_10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_list', models.ManyToManyField(to='core.QuestionSet10')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Quizs')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizDestributorModel_5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_list', models.ManyToManyField(to='core.QuestionSet5')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Quizs')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='QuizDestributorModel',
        ),
    ]
