# Generated by Django 3.0 on 2020-04-29 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200429_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizdestributormodel_10',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizdestributormodel_5',
            name='quiz',
        ),
    ]
