# Generated by Django 3.0 on 2020-05-02 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20200429_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizdestributormodel_10',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizdestributormodel_10',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizdestributormodel_10',
            name='name',
            field=models.CharField(default='ads', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizdestributormodel_5',
            name='author',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizdestributormodel_5',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizdestributormodel_5',
            name='name',
            field=models.CharField(default='asd', max_length=255),
            preserve_default=False,
        ),
    ]
