# Generated by Django 3.0 on 2020-05-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200502_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreboardmodel',
            name='quiz',
            field=models.CharField(max_length=255),
        ),
    ]
