# Generated by Django 3.0 on 2020-05-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200502_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreboardmodel',
            name='max_score',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
